language: cpp
dist: bionic
sudo: true

before_install:
    - sudo apt-get install cppcheck valgrind -y
script:
    - cppcheck --inconclusive --enable=all --check-config --suppress=missingIncludeSystem -I include src
    - ./ci/configure
    - cd build
    - make test
    - cd test
    - valgrind -v --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med  --track-origins=yes --child-silent-after-fork=yes ./graph_tests
